import { SceneLayerAsset, SceneLayerPreset } from '../rendering/SceneLayerTypes';

const baseLayer: Omit<SceneLayerAsset, 'file'> = {
    opacity: 1,
    blendMode: 'alpha',
    emissive: [1, 1, 1],
    yOffset: 0,
    zOffset: 0,
    widthScale: 1,
    height: 36,
    billboard: false,
    renderGroup: 0,
    alphaKey: 'texture',
    cameraOpacity: { front: 1, overview: 0.9 },
    parallaxStrength: 0,
    stageFit: 'full-stage',
};

const layer = (file: string | null, overrides: Partial<SceneLayerAsset>): SceneLayerAsset => ({
    ...baseLayer,
    file,
    ...overrides,
});

export const magicalForestLayerPreset: SceneLayerPreset = {
    id: 'forest',
    background: layer('bg_forest_v3_main.png', {
        opacity: 1,
        alphaKey: 'none',
        yOffset: -7.8,
        zOffset: 34,
        widthScale: 4.75,
        height: 38,
        renderGroup: 0,
        cameraOpacity: { front: 1, overview: 1 },
        parallaxStrength: 0.02,
        stageFit: 'full-stage',
    }),
    midground: layer('mid_forest_v3_alpha.png', {
        opacity: 0.94,
        yOffset: -7.8,
        zOffset: 27,
        widthScale: 4.75,
        height: 38,
        renderGroup: 0,
        cameraOpacity: { front: 0.95, overview: 0.82 },
        parallaxStrength: 0.07,
        stageFit: 'full-stage',
    }),
    platformBlendFog: layer('fx_forest_v3_alpha.png', {
        opacity: 0.22,
        blendMode: 'additive',
        emissive: [0.35, 0.9, 0.42],
        yOffset: -10.4,
        zOffset: 13,
        widthScale: 4.55,
        height: 26,
        renderGroup: 0,
        cameraOpacity: { front: 0.28, overview: 0.18 },
        parallaxStrength: 0.04,
        stageFit: 'lower-stage',
        scrollSpeedX: 0.001,
        alphaKey: 'texture',
    }),
    foreground: layer('fore_forest_v3_alpha.png', {
        opacity: 0.76,
        yOffset: -8.8,
        zOffset: -5.5,
        widthScale: 4.95,
        height: 40,
        renderGroup: 1,
        cameraOpacity: { front: 0.78, overview: 0.42 },
        parallaxStrength: 0.22,
        stageFit: 'foreground-frame',
    }),
    fxOverlay: layer('fx_forest_v3_alpha.png', {
        opacity: 0.18,
        blendMode: 'additive',
        emissive: [0.32, 0.9, 0.36],
        yOffset: -8.4,
        zOffset: -2.2,
        widthScale: 4.9,
        height: 39,
        renderGroup: 1,
        cameraOpacity: { front: 0.22, overview: 0.14 },
        parallaxStrength: 0.16,
        stageFit: 'fx-overlay',
        scrollSpeedX: 0.0015,
        alphaKey: 'texture',
    }),
    particleColor: [0.4, 1.0, 0.2],
    particleCount: 22,
    particleAlpha: [0.08, 0.26],
};

const simpleBiomePreset = (
    id: string,
    files: { background: string; midground: string; foreground: string; fxOverlay: string },
    tint: [number, number, number]
): SceneLayerPreset => ({
    id,
    background: layer(files.background, {
        opacity: 0.94,
        alphaKey: 'none',
        yOffset: -7.8,
        zOffset: 34,
        widthScale: 4.6,
        height: 38,
        cameraOpacity: { front: 1, overview: 0.95 },
    }),
    midground: layer(files.midground, {
        opacity: 0.86,
        yOffset: -7.8,
        zOffset: 27,
        widthScale: 4.6,
        height: 38,
        cameraOpacity: { front: 0.9, overview: 0.76 },
    }),
    platformBlendFog: layer(files.fxOverlay, {
        opacity: 0.2,
        blendMode: 'additive',
        emissive: tint,
        yOffset: -10.3,
        zOffset: 13,
        widthScale: 4.45,
        height: 26,
        cameraOpacity: { front: 0.25, overview: 0.16 },
        stageFit: 'lower-stage',
    }),
    foreground: layer(files.foreground, {
        opacity: 0.68,
        yOffset: -8.8,
        zOffset: -5.5,
        widthScale: 4.75,
        height: 40,
        renderGroup: 1,
        cameraOpacity: { front: 0.7, overview: 0.36 },
        stageFit: 'foreground-frame',
    }),
    fxOverlay: layer(files.fxOverlay, {
        opacity: 0.18,
        blendMode: 'additive',
        emissive: tint,
        yOffset: -8.4,
        zOffset: -2.2,
        widthScale: 4.75,
        height: 39,
        renderGroup: 1,
        cameraOpacity: { front: 0.2, overview: 0.12 },
        stageFit: 'fx-overlay',
        scrollSpeedX: 0.0015,
    }),
    particleColor: tint,
    particleCount: 30,
    particleAlpha: [0.1, 0.42],
});

export const SCENE_LAYER_PRESETS: Record<string, SceneLayerPreset> = {
    forest: magicalForestLayerPreset,
    plains: simpleBiomePreset('plains', {
        background: 'bg_plains_main.png',
        midground: 'mid_plains_hills.png',
        foreground: 'fore_plains_grass.png',
        fxOverlay: 'fx_plains_wind.png',
    }, [0.8, 0.95, 0.42]),
    mountain: simpleBiomePreset('mountain', {
        background: 'bg_mountain_main.png',
        midground: 'mid_mountain_rocks.png',
        foreground: 'fore_mountain_cliffs.png',
        fxOverlay: 'fx_mountain_fog.png',
    }, [0.55, 0.72, 1.0]),
    swamp: simpleBiomePreset('swamp', {
        background: 'bg_swamp_main.png',
        midground: 'mid_swamp_trees.png',
        foreground: 'fore_swamp_roots.png',
        fxOverlay: 'fx_swamp_mist.png',
    }, [0.2, 1.0, 0.3]),
    ruins: simpleBiomePreset('ruins', {
        background: 'bg_ruins_main.png',
        midground: 'mid_ruins_pillars.png',
        foreground: 'fore_ruins_arches.png',
        fxOverlay: 'fx_ruins_dust.png',
    }, [1.0, 0.7, 0.3]),
    city: simpleBiomePreset('city', {
        background: 'bg_city_main.png',
        midground: 'mid_city_buildings.png',
        foreground: 'fore_city_walls.png',
        fxOverlay: 'fx_city_smoke.png',
    }, [0.7, 0.8, 1.0]),
};
